[package]
name = "abc201"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc201-a", problem = { platform = "atcoder", contest = "abc201", index = "A", url = "https://atcoder.jp/contests/abc201/tasks/abc201_a" } }
b = { name = "abc201-b", problem = { platform = "atcoder", contest = "abc201", index = "B", url = "https://atcoder.jp/contests/abc201/tasks/abc201_b" } }
c = { name = "abc201-c", problem = { platform = "atcoder", contest = "abc201", index = "C", url = "https://atcoder.jp/contests/abc201/tasks/abc201_c" } }
d = { name = "abc201-d", problem = { platform = "atcoder", contest = "abc201", index = "D", url = "https://atcoder.jp/contests/abc201/tasks/abc201_d" } }
e = { name = "abc201-e", problem = { platform = "atcoder", contest = "abc201", index = "E", url = "https://atcoder.jp/contests/abc201/tasks/abc201_e" } }
f = { name = "abc201-f", problem = { platform = "atcoder", contest = "abc201", index = "F", url = "https://atcoder.jp/contests/abc201/tasks/abc201_f" } }

[[bin]]
name = "abc201-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc201-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc201-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc201-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc201-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc201-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.7", features = ["derive"] }
itertools = "=0.9.0"
num = "0.2.1"
