[package]
name = "abc150"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc150-a", problem = { platform = "atcoder", contest = "abc150", index = "A", url = "https://atcoder.jp/contests/abc150/tasks/abc150_a" } }
b = { name = "abc150-b", problem = { platform = "atcoder", contest = "abc150", index = "B", url = "https://atcoder.jp/contests/abc150/tasks/abc150_b" } }
c = { name = "abc150-c", problem = { platform = "atcoder", contest = "abc150", index = "C", url = "https://atcoder.jp/contests/abc150/tasks/abc150_c" } }
d = { name = "abc150-d", problem = { platform = "atcoder", contest = "abc150", index = "D", url = "https://atcoder.jp/contests/abc150/tasks/abc150_d" } }
e = { name = "abc150-e", problem = { platform = "atcoder", contest = "abc150", index = "E", url = "https://atcoder.jp/contests/abc150/tasks/abc150_e" } }
f = { name = "abc150-f", problem = { platform = "atcoder", contest = "abc150", index = "F", url = "https://atcoder.jp/contests/abc150/tasks/abc150_f" } }

[[bin]]
name = "abc150-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc150-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc150-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc150-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc150-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc150-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.6", features = ["derive"] }
itertools = "=0.9.0"
