[package]
name = "abc180"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc180-a", problem = { platform = "atcoder", contest = "abc180", index = "A", url = "https://atcoder.jp/contests/abc180/tasks/abc180_a" } }
b = { name = "abc180-b", problem = { platform = "atcoder", contest = "abc180", index = "B", url = "https://atcoder.jp/contests/abc180/tasks/abc180_b" } }
c = { name = "abc180-c", problem = { platform = "atcoder", contest = "abc180", index = "C", url = "https://atcoder.jp/contests/abc180/tasks/abc180_c" } }
d = { name = "abc180-d", problem = { platform = "atcoder", contest = "abc180", index = "D", url = "https://atcoder.jp/contests/abc180/tasks/abc180_d" } }
e = { name = "abc180-e", problem = { platform = "atcoder", contest = "abc180", index = "E", url = "https://atcoder.jp/contests/abc180/tasks/abc180_e" } }
f = { name = "abc180-f", problem = { platform = "atcoder", contest = "abc180", index = "F", url = "https://atcoder.jp/contests/abc180/tasks/abc180_f" } }

[[bin]]
name = "abc180-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc180-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc180-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc180-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc180-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc180-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.6", features = ["derive"] }
itertools = "=0.9.0"
