[package]
name = "abc156"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc156-a", problem = { platform = "atcoder", contest = "abc156", index = "A", url = "https://atcoder.jp/contests/abc156/tasks/abc156_a" } }
b = { name = "abc156-b", problem = { platform = "atcoder", contest = "abc156", index = "B", url = "https://atcoder.jp/contests/abc156/tasks/abc156_b" } }
c = { name = "abc156-c", problem = { platform = "atcoder", contest = "abc156", index = "C", url = "https://atcoder.jp/contests/abc156/tasks/abc156_c" } }
d = { name = "abc156-d", problem = { platform = "atcoder", contest = "abc156", index = "D", url = "https://atcoder.jp/contests/abc156/tasks/abc156_d" } }
e = { name = "abc156-e", problem = { platform = "atcoder", contest = "abc156", index = "E", url = "https://atcoder.jp/contests/abc156/tasks/abc156_e" } }
f = { name = "abc156-f", problem = { platform = "atcoder", contest = "abc156", index = "F", url = "https://atcoder.jp/contests/abc156/tasks/abc156_f" } }

[[bin]]
name = "abc156-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc156-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc156-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc156-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc156-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc156-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.6", features = ["derive"] }
itertools = "=0.9.0"
