[package]
name = "abc205"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete.bin]
abc205-a = { alias = "a", problem = "https://atcoder.jp/contests/abc205/tasks/abc205_a" }
abc205-b = { alias = "b", problem = "https://atcoder.jp/contests/abc205/tasks/abc205_b" }
abc205-c = { alias = "c", problem = "https://atcoder.jp/contests/abc205/tasks/abc205_c" }
abc205-d = { alias = "d", problem = "https://atcoder.jp/contests/abc205/tasks/abc205_d" }
abc205-e = { alias = "e", problem = "https://atcoder.jp/contests/abc205/tasks/abc205_e" }
abc205-f = { alias = "f", problem = "https://atcoder.jp/contests/abc205/tasks/abc205_f" }

[[bin]]
name = "abc205-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc205-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc205-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc205-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc205-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc205-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.7", features = ["derive"] }
itertools = "=0.9.0"
num = "0.2.1"
[dev-dependencies]
