# How to manage new workspace members ("include" | "exclude" | "focus")
#
# - `skip`:    Does not modify `[workspace]`
# - `include`: Adds the package to `workspace.members`
# - `exclude`: Adds the package to `workspace.exclude` and create a symlink to the `compete.toml`
# - `focus`:   Adds the package to `workspace.members` and remove the other from both of `workspace.{members, exclude}`
new-workspace-member = "include"

# Path to the test file (Liquid template)
#
# Variables:
#
# - `manifest_dir`: Package directory
# - `contest`:      Contest ID (e.g. "abc100")
# - `problem`:      Problem index (e.g. "a", "b")
#
# Additional filters:
#
# - `kebabcase`: Convert to kebab case (by using the `heck` crate)
test-suite = "./testcases/{{ contest }}/{{ problem | kebabcase }}.yml"
#test-suite = "{{ manifest_dir }}/testcases/{{ problem | kebabcase }}.yml"

# Open files with the command (`jq` command)
#
# VSCode:
open = '["code"] + (.paths | map([.src, .test_suite]) | flatten) + ["-a", .manifest_dir]'
# Emacs:
#open = '["emacsclient", "-n"] + (.paths | map([.src, .test_suite]) | flatten)'

[template]
platform = "atcoder"
manifest = "./cargo-compete-template/Cargo.toml"
src = "./cargo-compete-template/src/main.rs"

#[submit-via-binary]
#target = "x86_64-unknown-linux-musl"
##cross = "cross"
#strip = "strip"
##upx = "upx"
