[package]
name = "abc200"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc200-a", problem = { platform = "atcoder", contest = "abc200", index = "A", url = "https://atcoder.jp/contests/abc200/tasks/abc200_a" } }
b = { name = "abc200-b", problem = { platform = "atcoder", contest = "abc200", index = "B", url = "https://atcoder.jp/contests/abc200/tasks/abc200_b" } }
c = { name = "abc200-c", problem = { platform = "atcoder", contest = "abc200", index = "C", url = "https://atcoder.jp/contests/abc200/tasks/abc200_c" } }
d = { name = "abc200-d", problem = { platform = "atcoder", contest = "abc200", index = "D", url = "https://atcoder.jp/contests/abc200/tasks/abc200_d" } }
e = { name = "abc200-e", problem = { platform = "atcoder", contest = "abc200", index = "E", url = "https://atcoder.jp/contests/abc200/tasks/abc200_e" } }
f = { name = "abc200-f", problem = { platform = "atcoder", contest = "abc200", index = "F", url = "https://atcoder.jp/contests/abc200/tasks/abc200_f" } }

[[bin]]
name = "abc200-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc200-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc200-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc200-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc200-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc200-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.7", features = ["derive"] }
itertools = "=0.9.0"
num = "0.2.1"
