[package]
name = "abc147"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete.bin]
a = {name = "abc147-a",problem = {platform = "atcoder",contest = "abc147",index = "A"}}
b = {name = "abc147-b",problem = {platform = "atcoder",contest = "abc147",index = "B"}}
c = {name = "abc147-c",problem = {platform = "atcoder",contest = "abc147",index = "C"}}
d = {name = "abc147-d",problem = {platform = "atcoder",contest = "abc147",index = "D"}}
e = {name = "abc147-e",problem = {platform = "atcoder",contest = "abc147",index = "E"}}
f = {name = "abc147-f",problem = {platform = "atcoder",contest = "abc147",index = "F"}}

# dependencies added to new project
[dependencies]
proconio = { version = "0.4.1", features = ["derive"] }

[[bin]]
name = "abc147-a"
path = "./src/bin/a.rs"

[[bin]]
name = "abc147-b"
path = "./src/bin/b.rs"

[[bin]]
name = "abc147-c"
path = "./src/bin/c.rs"

[[bin]]
name = "abc147-d"
path = "./src/bin/d.rs"

[[bin]]
name = "abc147-e"
path = "./src/bin/e.rs"

[[bin]]
name = "abc147-f"
path = "./src/bin/f.rs"
