[package]
name = "abc147"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc147-a", problem = { platform = "atcoder", contest = "abc147", index = "A", url = "https://atcoder.jp/contests/abc147/tasks/abc147_a" } }
b = { name = "abc147-b", problem = { platform = "atcoder", contest = "abc147", index = "B", url = "https://atcoder.jp/contests/abc147/tasks/abc147_b" } }
c = { name = "abc147-c", problem = { platform = "atcoder", contest = "abc147", index = "C", url = "https://atcoder.jp/contests/abc147/tasks/abc147_c" } }
d = { name = "abc147-d", problem = { platform = "atcoder", contest = "abc147", index = "D", url = "https://atcoder.jp/contests/abc147/tasks/abc147_d" } }
e = { name = "abc147-e", problem = { platform = "atcoder", contest = "abc147", index = "E", url = "https://atcoder.jp/contests/abc147/tasks/abc147_e" } }
f = { name = "abc147-f", problem = { platform = "atcoder", contest = "abc147", index = "F", url = "https://atcoder.jp/contests/abc147/tasks/abc147_f" } }

[[bin]]
name = "abc147-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc147-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc147-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc147-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc147-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc147-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.7", features = ["derive"] }
itertools = "=0.9.0"
num = "0.2.1"
