[package]
name = "abc165"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc165-a", problem = { platform = "atcoder", contest = "abc165", index = "A", url = "https://atcoder.jp/contests/abc165/tasks/abc165_a" } }
b = { name = "abc165-b", problem = { platform = "atcoder", contest = "abc165", index = "B", url = "https://atcoder.jp/contests/abc165/tasks/abc165_b" } }
c = { name = "abc165-c", problem = { platform = "atcoder", contest = "abc165", index = "C", url = "https://atcoder.jp/contests/abc165/tasks/abc165_c" } }
d = { name = "abc165-d", problem = { platform = "atcoder", contest = "abc165", index = "D", url = "https://atcoder.jp/contests/abc165/tasks/abc165_d" } }
e = { name = "abc165-e", problem = { platform = "atcoder", contest = "abc165", index = "E", url = "https://atcoder.jp/contests/abc165/tasks/abc165_e" } }
f = { name = "abc165-f", problem = { platform = "atcoder", contest = "abc165", index = "F", url = "https://atcoder.jp/contests/abc165/tasks/abc165_f" } }

[[bin]]
name = "abc165-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc165-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc165-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc165-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc165-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc165-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.7", features = ["derive"] }
itertools = "=0.9.0"
num = "0.2.1"
