[package]
name = "abc136"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete.bin]
a = {name = "abc136-a",problem = {platform = "atcoder",contest = "abc136",index = "A"}}
b = {name = "abc136-b",problem = {platform = "atcoder",contest = "abc136",index = "B"}}
c = {name = "abc136-c",problem = {platform = "atcoder",contest = "abc136",index = "C"}}
d = {name = "abc136-d",problem = {platform = "atcoder",contest = "abc136",index = "D"}}
e = {name = "abc136-e",problem = {platform = "atcoder",contest = "abc136",index = "E"}}
f = {name = "abc136-f",problem = {platform = "atcoder",contest = "abc136",index = "F"}}

# dependencies added to new project
[dependencies]
proconio = { version = "0.4.1", features = ["derive"] }

[[bin]]
name = "abc136-a"
path = "./src/bin/a.rs"

[[bin]]
name = "abc136-b"
path = "./src/bin/b.rs"

[[bin]]
name = "abc136-c"
path = "./src/bin/c.rs"

[[bin]]
name = "abc136-d"
path = "./src/bin/d.rs"

[[bin]]
name = "abc136-e"
path = "./src/bin/e.rs"

[[bin]]
name = "abc136-f"
path = "./src/bin/f.rs"
