[package]
name = "abc136"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc136-a", problem = { platform = "atcoder", contest = "abc136", index = "A", url = "https://atcoder.jp/contests/abc136/tasks/abc136_a" } }
b = { name = "abc136-b", problem = { platform = "atcoder", contest = "abc136", index = "B", url = "https://atcoder.jp/contests/abc136/tasks/abc136_b" } }
c = { name = "abc136-c", problem = { platform = "atcoder", contest = "abc136", index = "C", url = "https://atcoder.jp/contests/abc136/tasks/abc136_c" } }
d = { name = "abc136-d", problem = { platform = "atcoder", contest = "abc136", index = "D", url = "https://atcoder.jp/contests/abc136/tasks/abc136_d" } }
e = { name = "abc136-e", problem = { platform = "atcoder", contest = "abc136", index = "E", url = "https://atcoder.jp/contests/abc136/tasks/abc136_e" } }
f = { name = "abc136-f", problem = { platform = "atcoder", contest = "abc136", index = "F", url = "https://atcoder.jp/contests/abc136/tasks/abc136_f" } }

[[bin]]
name = "abc136-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc136-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc136-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc136-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc136-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc136-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.7", features = ["derive"] }
itertools = "=0.9.0"
num = "0.2.1"
