[package]
name = "abc151"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc151-a", problem = { platform = "atcoder", contest = "abc151", index = "A", url = "https://atcoder.jp/contests/abc151/tasks/abc151_a" } }
b = { name = "abc151-b", problem = { platform = "atcoder", contest = "abc151", index = "B", url = "https://atcoder.jp/contests/abc151/tasks/abc151_b" } }
c = { name = "abc151-c", problem = { platform = "atcoder", contest = "abc151", index = "C", url = "https://atcoder.jp/contests/abc151/tasks/abc151_c" } }
d = { name = "abc151-d", problem = { platform = "atcoder", contest = "abc151", index = "D", url = "https://atcoder.jp/contests/abc151/tasks/abc151_d" } }
e = { name = "abc151-e", problem = { platform = "atcoder", contest = "abc151", index = "E", url = "https://atcoder.jp/contests/abc151/tasks/abc151_e" } }
f = { name = "abc151-f", problem = { platform = "atcoder", contest = "abc151", index = "F", url = "https://atcoder.jp/contests/abc151/tasks/abc151_f" } }

[[bin]]
name = "abc151-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc151-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc151-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc151-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc151-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc151-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.7", features = ["derive"] }
itertools = "=0.9.0"
num = "0.2.1"
