[package]
name = "abc171"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete.bin]
a = {name = "abc171-a",problem = {platform = "atcoder",contest = "abc171",index = "A"}}
b = {name = "abc171-b",problem = {platform = "atcoder",contest = "abc171",index = "B"}}
c = {name = "abc171-c",problem = {platform = "atcoder",contest = "abc171",index = "C"}}
d = {name = "abc171-d",problem = {platform = "atcoder",contest = "abc171",index = "D"}}
e = {name = "abc171-e",problem = {platform = "atcoder",contest = "abc171",index = "E"}}
f = {name = "abc171-f",problem = {platform = "atcoder",contest = "abc171",index = "F"}}

# dependencies added to new project
[dependencies]
proconio = { version = "0.4.1", features = ["derive"] }
itertools = "0.8.2"

[[bin]]
name = "abc171-a"
path = "./src/bin/a.rs"

[[bin]]
name = "abc171-b"
path = "./src/bin/b.rs"

[[bin]]
name = "abc171-c"
path = "./src/bin/c.rs"

[[bin]]
name = "abc171-d"
path = "./src/bin/d.rs"

[[bin]]
name = "abc171-e"
path = "./src/bin/e.rs"

[[bin]]
name = "abc171-f"
path = "./src/bin/f.rs"
