[package]
name = "abc158"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc158-a", problem = { platform = "atcoder", contest = "abc158", index = "A", url = "https://atcoder.jp/contests/abc158/tasks/abc158_a" } }
b = { name = "abc158-b", problem = { platform = "atcoder", contest = "abc158", index = "B", url = "https://atcoder.jp/contests/abc158/tasks/abc158_b" } }
c = { name = "abc158-c", problem = { platform = "atcoder", contest = "abc158", index = "C", url = "https://atcoder.jp/contests/abc158/tasks/abc158_c" } }
d = { name = "abc158-d", problem = { platform = "atcoder", contest = "abc158", index = "D", url = "https://atcoder.jp/contests/abc158/tasks/abc158_d" } }
e = { name = "abc158-e", problem = { platform = "atcoder", contest = "abc158", index = "E", url = "https://atcoder.jp/contests/abc158/tasks/abc158_e" } }
f = { name = "abc158-f", problem = { platform = "atcoder", contest = "abc158", index = "F", url = "https://atcoder.jp/contests/abc158/tasks/abc158_f" } }

[[bin]]
name = "abc158-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc158-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc158-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc158-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc158-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc158-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.6", features = ["derive"] }
itertools = "=0.9.0"
