[package]
name = "abc169"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc169-a", problem = { platform = "atcoder", contest = "abc169", index = "A", url = "https://atcoder.jp/contests/abc169/tasks/abc169_a" } }
b = { name = "abc169-b", problem = { platform = "atcoder", contest = "abc169", index = "B", url = "https://atcoder.jp/contests/abc169/tasks/abc169_b" } }
c = { name = "abc169-c", problem = { platform = "atcoder", contest = "abc169", index = "C", url = "https://atcoder.jp/contests/abc169/tasks/abc169_c" } }
d = { name = "abc169-d", problem = { platform = "atcoder", contest = "abc169", index = "D", url = "https://atcoder.jp/contests/abc169/tasks/abc169_d" } }
e = { name = "abc169-e", problem = { platform = "atcoder", contest = "abc169", index = "E", url = "https://atcoder.jp/contests/abc169/tasks/abc169_e" } }
f = { name = "abc169-f", problem = { platform = "atcoder", contest = "abc169", index = "F", url = "https://atcoder.jp/contests/abc169/tasks/abc169_f" } }

[[bin]]
name = "abc169-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc169-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc169-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc169-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc169-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc169-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.7", features = ["derive"] }
itertools = "=0.9.0"
num = "0.2.1"
