[package]
name = "atc001"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "atc001-a", problem = { platform = "atcoder", contest = "atc001", index = "A", url = "https://atcoder.jp/contests/atc001/tasks/dfs_a" } }
b = { name = "atc001-b", problem = { platform = "atcoder", contest = "atc001", index = "B", url = "https://atcoder.jp/contests/atc001/tasks/unionfind_a" } }
c = { name = "atc001-c", problem = { platform = "atcoder", contest = "atc001", index = "C", url = "https://atcoder.jp/contests/atc001/tasks/fft_c" } }

[[bin]]
name = "atc001-a"
path = "src/bin/a.rs"

[[bin]]
name = "atc001-b"
path = "src/bin/b.rs"

[[bin]]
name = "atc001-c"
path = "src/bin/c.rs"
[dependencies]
proconio = { version = "0.3.7", features = ["derive"] }
itertools = "=0.9.0"
num = "0.2.1"
