[package]
name = "abc175"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc175-a", problem = { platform = "atcoder", contest = "abc175", index = "A", url = "https://atcoder.jp/contests/abc175/tasks/abc175_a" } }
b = { name = "abc175-b", problem = { platform = "atcoder", contest = "abc175", index = "B", url = "https://atcoder.jp/contests/abc175/tasks/abc175_b" } }
c = { name = "abc175-c", problem = { platform = "atcoder", contest = "abc175", index = "C", url = "https://atcoder.jp/contests/abc175/tasks/abc175_c" } }
d = { name = "abc175-d", problem = { platform = "atcoder", contest = "abc175", index = "D", url = "https://atcoder.jp/contests/abc175/tasks/abc175_d" } }
e = { name = "abc175-e", problem = { platform = "atcoder", contest = "abc175", index = "E", url = "https://atcoder.jp/contests/abc175/tasks/abc175_e" } }
f = { name = "abc175-f", problem = { platform = "atcoder", contest = "abc175", index = "F", url = "https://atcoder.jp/contests/abc175/tasks/abc175_f" } }

[[bin]]
name = "abc175-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc175-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc175-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc175-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc175-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc175-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.6", features = ["derive"] }
itertools = "=0.9.0"
