[package]
name = "abc167"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc167-a", problem = { platform = "atcoder", contest = "abc167", index = "A", url = "https://atcoder.jp/contests/abc167/tasks/abc167_a" } }
b = { name = "abc167-b", problem = { platform = "atcoder", contest = "abc167", index = "B", url = "https://atcoder.jp/contests/abc167/tasks/abc167_b" } }
c = { name = "abc167-c", problem = { platform = "atcoder", contest = "abc167", index = "C", url = "https://atcoder.jp/contests/abc167/tasks/abc167_c" } }
d = { name = "abc167-d", problem = { platform = "atcoder", contest = "abc167", index = "D", url = "https://atcoder.jp/contests/abc167/tasks/abc167_d" } }
e = { name = "abc167-e", problem = { platform = "atcoder", contest = "abc167", index = "E", url = "https://atcoder.jp/contests/abc167/tasks/abc167_e" } }
f = { name = "abc167-f", problem = { platform = "atcoder", contest = "abc167", index = "F", url = "https://atcoder.jp/contests/abc167/tasks/abc167_f" } }

[[bin]]
name = "abc167-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc167-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc167-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc167-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc167-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc167-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.7", features = ["derive"] }
itertools = "=0.9.0"
num = "0.2.1"
