[package]
name = "abc168"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc168-a", problem = { platform = "atcoder", contest = "abc168", index = "A", url = "https://atcoder.jp/contests/abc168/tasks/abc168_a" } }
b = { name = "abc168-b", problem = { platform = "atcoder", contest = "abc168", index = "B", url = "https://atcoder.jp/contests/abc168/tasks/abc168_b" } }
c = { name = "abc168-c", problem = { platform = "atcoder", contest = "abc168", index = "C", url = "https://atcoder.jp/contests/abc168/tasks/abc168_c" } }
d = { name = "abc168-d", problem = { platform = "atcoder", contest = "abc168", index = "D", url = "https://atcoder.jp/contests/abc168/tasks/abc168_d" } }
e = { name = "abc168-e", problem = { platform = "atcoder", contest = "abc168", index = "E", url = "https://atcoder.jp/contests/abc168/tasks/abc168_e" } }
f = { name = "abc168-f", problem = { platform = "atcoder", contest = "abc168", index = "F", url = "https://atcoder.jp/contests/abc168/tasks/abc168_f" } }

[[bin]]
name = "abc168-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc168-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc168-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc168-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc168-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc168-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.7", features = ["derive"] }
itertools = "=0.9.0"
num = "0.2.1"
