[package]
name = "abc202"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc202-a", problem = { platform = "atcoder", contest = "abc202", index = "A", url = "https://atcoder.jp/contests/abc202/tasks/abc202_a" } }
b = { name = "abc202-b", problem = { platform = "atcoder", contest = "abc202", index = "B", url = "https://atcoder.jp/contests/abc202/tasks/abc202_b" } }
c = { name = "abc202-c", problem = { platform = "atcoder", contest = "abc202", index = "C", url = "https://atcoder.jp/contests/abc202/tasks/abc202_c" } }
d = { name = "abc202-d", problem = { platform = "atcoder", contest = "abc202", index = "D", url = "https://atcoder.jp/contests/abc202/tasks/abc202_d" } }
e = { name = "abc202-e", problem = { platform = "atcoder", contest = "abc202", index = "E", url = "https://atcoder.jp/contests/abc202/tasks/abc202_e" } }
f = { name = "abc202-f", problem = { platform = "atcoder", contest = "abc202", index = "F", url = "https://atcoder.jp/contests/abc202/tasks/abc202_f" } }

[[bin]]
name = "abc202-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc202-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc202-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc202-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc202-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc202-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.7", features = ["derive"] }
itertools = "=0.9.0"
num = "0.2.1"
