[package]
name = "abc191"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc191-a", problem = { platform = "atcoder", contest = "abc191", index = "A", url = "https://atcoder.jp/contests/abc191/tasks/abc191_a" } }
b = { name = "abc191-b", problem = { platform = "atcoder", contest = "abc191", index = "B", url = "https://atcoder.jp/contests/abc191/tasks/abc191_b" } }
c = { name = "abc191-c", problem = { platform = "atcoder", contest = "abc191", index = "C", url = "https://atcoder.jp/contests/abc191/tasks/abc191_c" } }
d = { name = "abc191-d", problem = { platform = "atcoder", contest = "abc191", index = "D", url = "https://atcoder.jp/contests/abc191/tasks/abc191_d" } }
e = { name = "abc191-e", problem = { platform = "atcoder", contest = "abc191", index = "E", url = "https://atcoder.jp/contests/abc191/tasks/abc191_e" } }
f = { name = "abc191-f", problem = { platform = "atcoder", contest = "abc191", index = "F", url = "https://atcoder.jp/contests/abc191/tasks/abc191_f" } }

[[bin]]
name = "abc191-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc191-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc191-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc191-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc191-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc191-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.6", features = ["derive"] }
itertools = "=0.9.0"
