[package]
name = "abc144"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete.bin]
a = {name = "abc144-a",problem = {platform = "atcoder",contest = "abc144",index = "A"}}
b = {name = "abc144-b",problem = {platform = "atcoder",contest = "abc144",index = "B"}}
c = {name = "abc144-c",problem = {platform = "atcoder",contest = "abc144",index = "C"}}
d = {name = "abc144-d",problem = {platform = "atcoder",contest = "abc144",index = "D"}}
e = {name = "abc144-e",problem = {platform = "atcoder",contest = "abc144",index = "E"}}
f = {name = "abc144-f",problem = {platform = "atcoder",contest = "abc144",index = "F"}}

# dependencies added to new project
[dependencies]
proconio = { version = "0.4.1", features = ["derive"] }

[[bin]]
name = "abc144-a"
path = "./src/bin/a.rs"

[[bin]]
name = "abc144-b"
path = "./src/bin/b.rs"

[[bin]]
name = "abc144-c"
path = "./src/bin/c.rs"

[[bin]]
name = "abc144-d"
path = "./src/bin/d.rs"

[[bin]]
name = "abc144-e"
path = "./src/bin/e.rs"

[[bin]]
name = "abc144-f"
path = "./src/bin/f.rs"
