[package]
name = "arc031"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "arc031-a", problem = { platform = "atcoder", contest = "arc031", index = "A", url = "https://atcoder.jp/contests/arc031/tasks/arc031_1" } }
b = { name = "arc031-b", problem = { platform = "atcoder", contest = "arc031", index = "B", url = "https://atcoder.jp/contests/arc031/tasks/arc031_2" } }
c = { name = "arc031-c", problem = { platform = "atcoder", contest = "arc031", index = "C", url = "https://atcoder.jp/contests/arc031/tasks/arc031_3" } }
d = { name = "arc031-d", problem = { platform = "atcoder", contest = "arc031", index = "D", url = "https://atcoder.jp/contests/arc031/tasks/arc031_4" } }

[[bin]]
name = "arc031-a"
path = "src/bin/a.rs"

[[bin]]
name = "arc031-b"
path = "src/bin/b.rs"

[[bin]]
name = "arc031-c"
path = "src/bin/c.rs"

[[bin]]
name = "arc031-d"
path = "src/bin/d.rs"
[dependencies]
proconio = { version = "0.3.7", features = ["derive"] }
itertools = "=0.9.0"
num = "0.2.1"
