[package]
name = "abc170"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc170-a", problem = { platform = "atcoder", contest = "abc170", index = "A", url = "https://atcoder.jp/contests/abc170/tasks/abc170_a" } }
b = { name = "abc170-b", problem = { platform = "atcoder", contest = "abc170", index = "B", url = "https://atcoder.jp/contests/abc170/tasks/abc170_b" } }
c = { name = "abc170-c", problem = { platform = "atcoder", contest = "abc170", index = "C", url = "https://atcoder.jp/contests/abc170/tasks/abc170_c" } }
d = { name = "abc170-d", problem = { platform = "atcoder", contest = "abc170", index = "D", url = "https://atcoder.jp/contests/abc170/tasks/abc170_d" } }
e = { name = "abc170-e", problem = { platform = "atcoder", contest = "abc170", index = "E", url = "https://atcoder.jp/contests/abc170/tasks/abc170_e" } }
f = { name = "abc170-f", problem = { platform = "atcoder", contest = "abc170", index = "F", url = "https://atcoder.jp/contests/abc170/tasks/abc170_f" } }

[[bin]]
name = "abc170-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc170-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc170-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc170-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc170-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc170-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.7", features = ["derive"] }
itertools = "=0.9.0"
num = "0.2.1"
