[package]
name = "abc138"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc138-a", problem = { platform = "atcoder", contest = "abc138", index = "A", url = "https://atcoder.jp/contests/abc138/tasks/abc138_a" } }
b = { name = "abc138-b", problem = { platform = "atcoder", contest = "abc138", index = "B", url = "https://atcoder.jp/contests/abc138/tasks/abc138_b" } }
c = { name = "abc138-c", problem = { platform = "atcoder", contest = "abc138", index = "C", url = "https://atcoder.jp/contests/abc138/tasks/abc138_c" } }
d = { name = "abc138-d", problem = { platform = "atcoder", contest = "abc138", index = "D", url = "https://atcoder.jp/contests/abc138/tasks/abc138_d" } }
e = { name = "abc138-e", problem = { platform = "atcoder", contest = "abc138", index = "E", url = "https://atcoder.jp/contests/abc138/tasks/abc138_e" } }
f = { name = "abc138-f", problem = { platform = "atcoder", contest = "abc138", index = "F", url = "https://atcoder.jp/contests/abc138/tasks/abc138_f" } }

[[bin]]
name = "abc138-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc138-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc138-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc138-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc138-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc138-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.7", features = ["derive"] }
itertools = "=0.9.0"
num = "0.2.1"
