[package]
name = "abc209"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete.bin]
abc209-a = { alias = "a", problem = "https://atcoder.jp/contests/abc209/tasks/abc209_a" }
abc209-b = { alias = "b", problem = "https://atcoder.jp/contests/abc209/tasks/abc209_b" }
abc209-c = { alias = "c", problem = "https://atcoder.jp/contests/abc209/tasks/abc209_c" }
abc209-d = { alias = "d", problem = "https://atcoder.jp/contests/abc209/tasks/abc209_d" }
abc209-e = { alias = "e", problem = "https://atcoder.jp/contests/abc209/tasks/abc209_e" }
abc209-f = { alias = "f", problem = "https://atcoder.jp/contests/abc209/tasks/abc209_f" }

[[bin]]
name = "abc209-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc209-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc209-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc209-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc209-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc209-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.7", features = ["derive"] }
itertools = "=0.9.0"
num = "0.2.1"
[dev-dependencies]
