[package]
name = "abc179"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc179-a", problem = { platform = "atcoder", contest = "abc179", index = "A", url = "https://atcoder.jp/contests/abc179/tasks/abc179_a" } }
b = { name = "abc179-b", problem = { platform = "atcoder", contest = "abc179", index = "B", url = "https://atcoder.jp/contests/abc179/tasks/abc179_b" } }
c = { name = "abc179-c", problem = { platform = "atcoder", contest = "abc179", index = "C", url = "https://atcoder.jp/contests/abc179/tasks/abc179_c" } }
d = { name = "abc179-d", problem = { platform = "atcoder", contest = "abc179", index = "D", url = "https://atcoder.jp/contests/abc179/tasks/abc179_d" } }
e = { name = "abc179-e", problem = { platform = "atcoder", contest = "abc179", index = "E", url = "https://atcoder.jp/contests/abc179/tasks/abc179_e" } }
f = { name = "abc179-f", problem = { platform = "atcoder", contest = "abc179", index = "F", url = "https://atcoder.jp/contests/abc179/tasks/abc179_f" } }

[[bin]]
name = "abc179-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc179-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc179-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc179-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc179-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc179-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.7", features = ["derive"] }
itertools = "=0.9.0"
num = "0.2.1"
