[package]
name = "abc193"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc193-a", problem = { platform = "atcoder", contest = "abc193", index = "A", url = "https://atcoder.jp/contests/abc193/tasks/abc193_a" } }
b = { name = "abc193-b", problem = { platform = "atcoder", contest = "abc193", index = "B", url = "https://atcoder.jp/contests/abc193/tasks/abc193_b" } }
c = { name = "abc193-c", problem = { platform = "atcoder", contest = "abc193", index = "C", url = "https://atcoder.jp/contests/abc193/tasks/abc193_c" } }
d = { name = "abc193-d", problem = { platform = "atcoder", contest = "abc193", index = "D", url = "https://atcoder.jp/contests/abc193/tasks/abc193_d" } }
e = { name = "abc193-e", problem = { platform = "atcoder", contest = "abc193", index = "E", url = "https://atcoder.jp/contests/abc193/tasks/abc193_e" } }
f = { name = "abc193-f", problem = { platform = "atcoder", contest = "abc193", index = "F", url = "https://atcoder.jp/contests/abc193/tasks/abc193_f" } }

[[bin]]
name = "abc193-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc193-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc193-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc193-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc193-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc193-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.7", features = ["derive"] }
itertools = "=0.9.0"
num = "0.2.1"
