[package]
name = "abc145"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc145-a", problem = { platform = "atcoder", contest = "abc145", index = "A", url = "https://atcoder.jp/contests/abc145/tasks/abc145_a" } }
b = { name = "abc145-b", problem = { platform = "atcoder", contest = "abc145", index = "B", url = "https://atcoder.jp/contests/abc145/tasks/abc145_b" } }
c = { name = "abc145-c", problem = { platform = "atcoder", contest = "abc145", index = "C", url = "https://atcoder.jp/contests/abc145/tasks/abc145_c" } }
d = { name = "abc145-d", problem = { platform = "atcoder", contest = "abc145", index = "D", url = "https://atcoder.jp/contests/abc145/tasks/abc145_d" } }
e = { name = "abc145-e", problem = { platform = "atcoder", contest = "abc145", index = "E", url = "https://atcoder.jp/contests/abc145/tasks/abc145_e" } }
f = { name = "abc145-f", problem = { platform = "atcoder", contest = "abc145", index = "F", url = "https://atcoder.jp/contests/abc145/tasks/abc145_f" } }

[[bin]]
name = "abc145-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc145-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc145-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc145-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc145-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc145-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.6", features = ["derive"] }
itertools = "=0.9.0"
