[package]
name = "abc194"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc194-a", problem = { platform = "atcoder", contest = "abc194", index = "A", url = "https://atcoder.jp/contests/abc194/tasks/abc194_a" } }
b = { name = "abc194-b", problem = { platform = "atcoder", contest = "abc194", index = "B", url = "https://atcoder.jp/contests/abc194/tasks/abc194_b" } }
c = { name = "abc194-c", problem = { platform = "atcoder", contest = "abc194", index = "C", url = "https://atcoder.jp/contests/abc194/tasks/abc194_c" } }
d = { name = "abc194-d", problem = { platform = "atcoder", contest = "abc194", index = "D", url = "https://atcoder.jp/contests/abc194/tasks/abc194_d" } }
e = { name = "abc194-e", problem = { platform = "atcoder", contest = "abc194", index = "E", url = "https://atcoder.jp/contests/abc194/tasks/abc194_e" } }
f = { name = "abc194-f", problem = { platform = "atcoder", contest = "abc194", index = "F", url = "https://atcoder.jp/contests/abc194/tasks/abc194_f" } }

[[bin]]
name = "abc194-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc194-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc194-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc194-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc194-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc194-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.7", features = ["derive"] }
itertools = "=0.9.0"
