[package]
name = "abc174"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc174-a", problem = { platform = "atcoder", contest = "abc174", index = "A", url = "https://atcoder.jp/contests/abc174/tasks/abc174_a" } }
b = { name = "abc174-b", problem = { platform = "atcoder", contest = "abc174", index = "B", url = "https://atcoder.jp/contests/abc174/tasks/abc174_b" } }
c = { name = "abc174-c", problem = { platform = "atcoder", contest = "abc174", index = "C", url = "https://atcoder.jp/contests/abc174/tasks/abc174_c" } }
d = { name = "abc174-d", problem = { platform = "atcoder", contest = "abc174", index = "D", url = "https://atcoder.jp/contests/abc174/tasks/abc174_d" } }
e = { name = "abc174-e", problem = { platform = "atcoder", contest = "abc174", index = "E", url = "https://atcoder.jp/contests/abc174/tasks/abc174_e" } }
f = { name = "abc174-f", problem = { platform = "atcoder", contest = "abc174", index = "F", url = "https://atcoder.jp/contests/abc174/tasks/abc174_f" } }

[[bin]]
name = "abc174-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc174-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc174-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc174-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc174-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc174-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.7", features = ["derive"] }
itertools = "=0.9.0"
