[package]
name = "abc204"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc204-a", problem = { platform = "atcoder", contest = "abc204", index = "A", url = "https://atcoder.jp/contests/abc204/tasks/abc204_a" } }
b = { name = "abc204-b", problem = { platform = "atcoder", contest = "abc204", index = "B", url = "https://atcoder.jp/contests/abc204/tasks/abc204_b" } }
c = { name = "abc204-c", problem = { platform = "atcoder", contest = "abc204", index = "C", url = "https://atcoder.jp/contests/abc204/tasks/abc204_c" } }
d = { name = "abc204-d", problem = { platform = "atcoder", contest = "abc204", index = "D", url = "https://atcoder.jp/contests/abc204/tasks/abc204_d" } }
e = { name = "abc204-e", problem = { platform = "atcoder", contest = "abc204", index = "E", url = "https://atcoder.jp/contests/abc204/tasks/abc204_e" } }
f = { name = "abc204-f", problem = { platform = "atcoder", contest = "abc204", index = "F", url = "https://atcoder.jp/contests/abc204/tasks/abc204_f" } }

[[bin]]
name = "abc204-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc204-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc204-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc204-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc204-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc204-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.7", features = ["derive"] }
itertools = "=0.9.0"
num = "0.2.1"
