[package]
name = "pakencamp-2019-day3"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "pakencamp-2019-day3-a", problem = { platform = "atcoder", contest = "pakencamp-2019-day3", index = "A", url = "https://atcoder.jp/contests/pakencamp-2019-day3/tasks/pakencamp_2019_day3_a" } }
b = { name = "pakencamp-2019-day3-b", problem = { platform = "atcoder", contest = "pakencamp-2019-day3", index = "B", url = "https://atcoder.jp/contests/pakencamp-2019-day3/tasks/pakencamp_2019_day3_b" } }
c = { name = "pakencamp-2019-day3-c", problem = { platform = "atcoder", contest = "pakencamp-2019-day3", index = "C", url = "https://atcoder.jp/contests/pakencamp-2019-day3/tasks/pakencamp_2019_day3_c" } }
d = { name = "pakencamp-2019-day3-d", problem = { platform = "atcoder", contest = "pakencamp-2019-day3", index = "D", url = "https://atcoder.jp/contests/pakencamp-2019-day3/tasks/pakencamp_2019_day3_d" } }
e = { name = "pakencamp-2019-day3-e", problem = { platform = "atcoder", contest = "pakencamp-2019-day3", index = "E", url = "https://atcoder.jp/contests/pakencamp-2019-day3/tasks/pakencamp_2019_day3_e" } }
f = { name = "pakencamp-2019-day3-f", problem = { platform = "atcoder", contest = "pakencamp-2019-day3", index = "F", url = "https://atcoder.jp/contests/pakencamp-2019-day3/tasks/pakencamp_2019_day3_f" } }
g = { name = "pakencamp-2019-day3-g", problem = { platform = "atcoder", contest = "pakencamp-2019-day3", index = "G", url = "https://atcoder.jp/contests/pakencamp-2019-day3/tasks/pakencamp_2019_day3_g" } }
h = { name = "pakencamp-2019-day3-h", problem = { platform = "atcoder", contest = "pakencamp-2019-day3", index = "H", url = "https://atcoder.jp/contests/pakencamp-2019-day3/tasks/pakencamp_2019_day3_h" } }

[[bin]]
name = "pakencamp-2019-day3-a"
path = "src/bin/a.rs"

[[bin]]
name = "pakencamp-2019-day3-b"
path = "src/bin/b.rs"

[[bin]]
name = "pakencamp-2019-day3-c"
path = "src/bin/c.rs"

[[bin]]
name = "pakencamp-2019-day3-d"
path = "src/bin/d.rs"

[[bin]]
name = "pakencamp-2019-day3-e"
path = "src/bin/e.rs"

[[bin]]
name = "pakencamp-2019-day3-f"
path = "src/bin/f.rs"

[[bin]]
name = "pakencamp-2019-day3-g"
path = "src/bin/g.rs"

[[bin]]
name = "pakencamp-2019-day3-h"
path = "src/bin/h.rs"
[dependencies]
proconio = { version = "0.3.7", features = ["derive"] }
itertools = "=0.9.0"
