[package]
name = "abc178"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc178-a", problem = { platform = "atcoder", contest = "abc178", index = "A", url = "https://atcoder.jp/contests/abc178/tasks/abc178_a" } }
b = { name = "abc178-b", problem = { platform = "atcoder", contest = "abc178", index = "B", url = "https://atcoder.jp/contests/abc178/tasks/abc178_b" } }
c = { name = "abc178-c", problem = { platform = "atcoder", contest = "abc178", index = "C", url = "https://atcoder.jp/contests/abc178/tasks/abc178_c" } }
d = { name = "abc178-d", problem = { platform = "atcoder", contest = "abc178", index = "D", url = "https://atcoder.jp/contests/abc178/tasks/abc178_d" } }
e = { name = "abc178-e", problem = { platform = "atcoder", contest = "abc178", index = "E", url = "https://atcoder.jp/contests/abc178/tasks/abc178_e" } }
f = { name = "abc178-f", problem = { platform = "atcoder", contest = "abc178", index = "F", url = "https://atcoder.jp/contests/abc178/tasks/abc178_f" } }

[[bin]]
name = "abc178-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc178-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc178-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc178-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc178-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc178-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.7", features = ["derive"] }
itertools = "=0.9.0"
num = "0.2.1"
