[package]
name = "abc164"
version = "0.1.0"
authors = ["moisutsu <moisutsu@gmail.com>"]
edition = "2018"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc164-a", problem = { platform = "atcoder", contest = "abc164", index = "A", url = "https://atcoder.jp/contests/abc164/tasks/abc164_a" } }
b = { name = "abc164-b", problem = { platform = "atcoder", contest = "abc164", index = "B", url = "https://atcoder.jp/contests/abc164/tasks/abc164_b" } }
c = { name = "abc164-c", problem = { platform = "atcoder", contest = "abc164", index = "C", url = "https://atcoder.jp/contests/abc164/tasks/abc164_c" } }
d = { name = "abc164-d", problem = { platform = "atcoder", contest = "abc164", index = "D", url = "https://atcoder.jp/contests/abc164/tasks/abc164_d" } }
e = { name = "abc164-e", problem = { platform = "atcoder", contest = "abc164", index = "E", url = "https://atcoder.jp/contests/abc164/tasks/abc164_e" } }
f = { name = "abc164-f", problem = { platform = "atcoder", contest = "abc164", index = "F", url = "https://atcoder.jp/contests/abc164/tasks/abc164_f" } }

[[bin]]
name = "abc164-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc164-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc164-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc164-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc164-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc164-f"
path = "src/bin/f.rs"
[dependencies]
proconio = { version = "0.3.7", features = ["derive"] }
itertools = "=0.9.0"
